apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: load-balancer-and-ingress-service.community.tanzu.vmware.com.1.7.2
  namespace: load-balancer-and-ingress-service
spec:
  refName: load-balancer-and-ingress-service.community.tanzu.vmware.com
  version: 1.7.2
  releaseNotes: "load-balancer-and-ingress-service 1.7.2"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/load-balancer-and-ingress-service@sha256:c8cfc75bdbbe16ef85428c49f2a98145a311ad05e158632584dd371471ade39b
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
