apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: oracle-cpi.community.tanzu.vmware.com.1.21.0
spec:
  refName: oracle-cpi.community.tanzu.vmware.com
  version: 1.22.1
  releaseNotes: oracle-cpi 1.22.1 https://github.com/oracle/oci-cloud-controller-manager
  licenses:
  - Apache 2.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tce/oracle-cpi@sha256:c701059fbb41c7021fed8c131b809c668b0d12e140734c3ea06fdb1b53690716
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
