#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ def is_toleration_specified(toleration):
#@   return toleration in yaml.decode(yaml.encode(data.values.metricsServer.config.tolerations))
#@ end

#@ default_tolerations = []
#@ is_master_specified = is_toleration_specified({"effect":"NoSchedule", "key":"node-role.kubernetes.io/master"})
#@ is_control_specified = is_toleration_specified({"effect":"NoSchedule", "key":"node-role.kubernetes.io/control-plane"})
#@ if is_master_specified and not is_control_specified:
#@   default_tolerations += [{"effect":"NoSchedule", "key":"node-role.kubernetes.io/control-plane"}]
#@ end

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "metrics-server"}})
---
spec:
  #@overlay/match-child-defaults missing_ok=True
  strategy:
    type: #@ data.values.metricsServer.config.updateStrategy
    #@overlay/remove
    rollingUpdate:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "metrics-server"})
      - args:
        #@overlay/match by=overlay.subset("--secure-port=443")
        - #@ "--secure-port=" + str(data.values.metricsServer.config.securePort)
        #@overlay/append
        - --kubelet-insecure-tls
        #@ for arg in data.values.metricsServer.config.args:
        #@overlay/append
        - #@ arg
        #@ end
        name: metrics-server
        ports:
          #@overlay/match by="name"
          - name: https
            containerPort: #@ data.values.metricsServer.config.securePort
        livenessProbe:
          failureThreshold: #@ data.values.metricsServer.config.probe.failureThreshold
          periodSeconds: #@ data.values.metricsServer.config.probe.periodSeconds
        readinessProbe:
          failureThreshold: #@ data.values.metricsServer.config.probe.failureThreshold
          periodSeconds: #@ data.values.metricsServer.config.probe.periodSeconds
      #@ if hasattr(data.values.metricsServer.config, 'tolerations') and data.values.metricsServer.config.tolerations:
      #@overlay/match missing_ok=True
      tolerations: #@ default_tolerations + data.values.metricsServer.config.tolerations
      #@ end
