apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.41.3
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.41.3
  releaseNotes: "kapp-controller 0.41.3 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:ce547748e7882fc4011bd0a2285657968a14f1b59b3e111009f71f8115fa8631
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
