apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.38.6
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.38.6
  releaseNotes: "kapp-controller 0.38.6 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:988955bae1706ed9569df4ff8b2ff4ce36056f7d672a6070871d805d64a30842
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
