#! schema.yaml

#@data/values-schema
#@schema/desc "OpenAPIv3 Schema for kube-vip-cloud-provider"
---
#@schema/desc "NodeSelector configuration applied to all the deployments"
#@schema/type any=True
nodeSelector:
deployment:
  #@schema/desc "Update strategy of deployments"
  #@schema/nullable
  updateStrategy: ""
  rollingUpdate:
    #@schema/desc "The maxUnavailable of rollingUpdate. Applied only if RollingUpdate is used as updateStrategy"
    #@schema/nullable
    maxUnavailable: 1
    #@schema/desc "The maxSurge of rollingUpdate. Applied only if RollingUpdate is used as updateStrategy"
    #@schema/nullable
    maxSurge: 0
#@schema/desc "Configurations for kube-vip-cloud-provider"
kubevipCloudProvider:
  #@schema/desc "A list of comma separated cidrs will be used to allocate IP for external load balancer."
  #@schema/nullable
  loadbalancerCIDRs: ""
  #@schema/desc "A list of comma separated IP ranges will be used to allocate IP for external load balancer."
  #@schema/nullable
  loadbalancerIPRanges: ""
